{
  "hash": "f1ceb04c6e32731c9da7c7ddbe975488",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Experiments\"\n---\n\n# Experiments\n\n::: {.callout-note icon=false}\n## Plain-Language Summary\nThis section describes the progression of experiments that led to the\ncurrent best result. Each experiment was a deliberate test of one specific\nhypothesis. Reading these in order reveals the key insights: the architecture\nworks, but only with the right initialisation strategy — and the depth of\nthat initialisation matters more than expected.\n:::\n\n---\n\n## Experimental Design Principles {#sec-exp-design}\n\nAll experiments share the following design constraints to ensure valid\ncomparison:\n\n- **Same gold dataset** — all experiments use the 9,660-record billable\n  gold layer derived from MedSynth FY2026.\n- **Same deterministic splits** — the 80/10/10 train/val/test split with\n  seed=42 is fixed for all experiments.\n- **Same test set** — the 966-record test set is held out and touched\n  only once per experiment for final evaluation.\n- **Same evaluation metrics** — all results report top-1 accuracy and\n  Macro F1 on the test set, with ECE and Coverage@0.7 for calibrated models.\n- **Logged provenance** — every run is logged to `outputs/experiments.json`\n  and `outputs/run.log` with full parameter records.\n\n---\n\n## Understanding the Evaluation Metrics {#sec-exp-metrics}\n\n::: {.callout-note icon=false}\n## Plain-Language Summary\nBefore presenting the experiment results, this section explains what the\nevaluation metrics actually measure and why we chose them. This is\nparticularly important for a 1,926-class problem where the choice of\naveraging method significantly affects what the number means — and whether\nit honestly reflects the system's capabilities.\n:::\n\n---\n\n### Top-1 Accuracy\n\nThe simplest metric: of all test records, what fraction did the model\npredict correctly?\n\n$$\\text{Accuracy} = \\frac{\\text{Correct predictions}}{\\text{Total predictions}} = \\frac{811}{966} = 83.9\\%$$\n\n**What it tells you:** How often the system gets the right answer.\n\n**What it conceals:** Whether errors are evenly distributed across all\n1,926 codes, or concentrated in a small number of difficult ones.\n\nIn multi-class classification, accuracy is equivalent to the **micro F1\nscore** — it pools all predictions together and measures overall volume\nof correct answers. A model that perfectly predicts the 100 most common\ncodes and fails on the remaining 1,826 could still achieve high accuracy\nif the common codes dominate the test set.\n\nIn our case the test set is **uniform** (approximately 5 records per code),\nso accuracy is a fair metric here. On real clinical data — where hypertension,\ndiabetes, and back pain dominate — it would be dangerously misleading.\n\n---\n\n### F1 Score: The Building Block\n\n**F1 score** for a single class is the harmonic mean of precision and recall:\n\n$$F1 = 2 \\times \\frac{\\text{Precision} \\times \\text{Recall}}{\\text{Precision} + \\text{Recall}}$$\n\nWhere precision and recall are computed using a **One-vs-Rest** approach —\neach class is treated as a binary classification problem in turn:\n\n- **Precision** — of all the times the model predicted this code, how\n  often was it correct? A high-precision model avoids false alarms.\n- **Recall** — of all the records that truly had this code, how many\n  did the model find? A high-recall model avoids missed detections.\n\nFor a concrete example using `I10` (Essential hypertension):\n\n| | Predicted I10 | Predicted other |\n|---|---|---|\n| **True I10** | 5 TP | 1 FN |\n| **True other** | 0 FP | 960 TN |\n\n$$\\text{Precision}_{I10} = \\frac{5}{5+0} = 1.00 \\qquad\n  \\text{Recall}_{I10} = \\frac{5}{5+1} = 0.833 \\qquad\n  F1_{I10} = 0.909$$\n\nThis per-class F1 is computed separately for all 1,926 codes. The question\nis then: how do we average 1,926 F1 scores into a single number?\n\n---\n\n### Three Averaging Strategies — and Why They Give Different Answers\n\nThere are three standard approaches, and the differences between them\nmatter enormously for a 1,926-class problem:\n\n**Macro average** computes the simple unweighted mean across all classes —\nevery class counts equally regardless of how many examples it has:\n\n$$\\text{Macro F1} = \\frac{1}{N} \\sum_{i=1}^{N} F1_i = \\frac{F1_{I10} + F1_{M25.562} + \\cdots + F1_{Z79.4}}{1926}$$\n\n**Weighted average** weights each class by its number of examples (its\n*support*). Classes with more training examples contribute more to the\nfinal score:\n\n$$\\text{Weighted F1} = \\sum_{i=1}^{N} \\frac{\\text{support}_i}{\\text{total}} \\times F1_i$$\n\n**Micro average** pools all True Positives, False Positives, and False\nNegatives across all classes before computing F1. For single-label\nclassification this is mathematically identical to accuracy:\n\n$$\\text{Micro F1} = \\text{Accuracy} = \\frac{\\sum TP_i}{\\sum (TP_i + FP_i)} = 83.9\\%$$\n\nThe table below summarises when each is appropriate:\n\n| Averaging | Treats classes | Best when |\n|---|---|---|\n| **Macro** | Equally | All classes matter equally regardless of frequency |\n| **Weighted** | Proportionally to frequency | Common classes matter more |\n| **Micro** | By prediction volume | Only overall throughput matters |\n\n---\n\n### Why This Project Uses Macro F1\n\n**Macro F1 is the right choice here for two reasons that reinforce each other.**\n\nFirst, **all 1,926 ICD-10 codes are clinically equally important.** A rare\ncode for a serious condition — say `A06.1` (chronic intestinal amoebiasis)\n— is no less significant than a common code for a routine condition like\n`M25.562` (pain in left knee). Getting the rare code wrong has the same\nconsequence as getting the common code wrong. Macro averaging encodes this\nequal importance directly.\n\nSecond, **the training set is deliberately uniform.** MedSynth has\napproximately 5 records per code by design. In this setting, weighted\naveraging would converge toward macro averaging anyway — but using macro\nexplicitly makes the equal-weight intention transparent.\n\n::: {.callout-important}\n## Macro F1 vs Accuracy: Why They Tell Different Stories Here\n\nFor this project both metrics are consistent because the test set is uniform.\nOn real clinical data they would diverge significantly:\n\nConsider a model that masters the 50 most common ICD-10 codes (covering\nroughly 60% of real encounters) but fails on the remaining 1,876 codes.\n\n- **Accuracy** (= Micro F1): ~60% — looks acceptable\n- **Macro F1**: ~0.03 — catastrophically poor\n\nMacro F1 exposes the failure that accuracy hides. This is why Macro F1\nis the primary metric in this project and why it should be the primary\nmetric for any automated coding system evaluated for clinical deployment.\n:::\n\n**What Macro F1 = 0.762 means in practice:** Averaged equally across all\n1,926 ICD-10 codes — from the highest-performing circulatory codes (~0.98)\nto the most difficult administrative codes (~0.62) — the model achieves\nan F1 of 0.762. This is a strong result for a 1,926-class problem with\n~4 training examples per class. Random guessing on this task would produce\na Macro F1 close to zero.\n\n---\n\n### Expected Calibration Error (ECE)\n\nECE measures whether the model's confidence scores are trustworthy.\nA perfectly calibrated model that says \"70% confident\" is correct\nexactly 70% of the time.\n\nECE is computed by bucketing predictions into confidence bins and measuring\nthe gap between average confidence and average accuracy in each bin:\n\n$$\\text{ECE} = \\sum_{b=1}^{B} \\frac{|B_b|}{n} \\left| \\text{acc}(B_b) - \\text{conf}(B_b) \\right|$$\n\n| ECE | Interpretation |\n|---|---|\n| < 0.05 | Excellent — confidence scores are reliable |\n| 0.05 – 0.15 | Good — minor overconfidence |\n| 0.15 – 0.30 | Moderate — needs treatment |\n| > 0.30 | Poor — confidence scores not meaningful |\n\nE-010 achieves **ECE = 0.034** after temperature scaling — excellent\ncalibration that makes the confidence threshold operationally meaningful.\nBefore calibration, the ECE was 0.640 — the model was severely overconfident\nand the threshold could not be trusted.\n\n---\n\n### Coverage@τ and Accuracy on Covered\n\nThese two metrics jointly describe the **selective automation** capability:\n\n- **Coverage@τ** — the fraction of test records where the model's top-1\n  confidence exceeds the threshold τ. At τ = 0.7: 82.1% of records are\n  auto-coded.\n\n- **Accuracy on covered** — the precision on the auto-coded subset.\n  At τ = 0.7: 95.2% of auto-coded predictions are correct.\n\nTogether they define the operating point: *how much can we automate, and\nat what quality?* A lower threshold automates more but at lower precision;\na higher threshold automates less but at higher precision. The τ = 0.7\noperating point was chosen as a practical balance point — see\n@sec-results-automation for the full threshold sweep.\n\n\n\n---\n\n## E-001: ICD-3 Flat Baseline {#sec-exp-e001}\n\n**Hypothesis:** Bio_ClinicalBERT fine-tuned on a reduced label space (ICD-3\nstem codes, 675 classes) can serve as a strong baseline and as a source of\ntransfer weights for later experiments.\n\n**Setup:** Flat 675-way classification. Labels are derived by truncating\neach ICD-10 code to its first three characters (e.g. `M25.562` → `M25`).\nThis groups related codes together and reduces the label space by approximately\n3×.\n\n| Parameter | Value |\n|---|---|\n| Label scheme | ICD-3 (675 classes) |\n| Epochs | 30 |\n| Learning rate | 2×10⁻⁵ |\n| Training records | 7,728 |\n\n**Result:**\n\n| Metric | Value |\n|---|---|\n| Test accuracy | 87.2% |\n| Macro F1 | 0.841 |\n| Best epoch | 28 |\n\n: E-001 results. {#tbl-exp-e001}\n\n**Interpretation:** 87.2% accuracy on a 675-way classification task from ~11\ntraining examples per class is a strong result. The model demonstrates that\nBio_ClinicalBERT can learn useful ICD-10 representations from this limited\ndata regime.\n\nNote that E-001 is **not directly comparable** to later experiments — it\npredicts ICD-3 stems, not full billable ICD-10 codes. A prediction of `M25`\nis much easier than predicting `M25.562` specifically.\n\n**Role in subsequent experiments:** The E-001 encoder, having learned\nto distinguish ICD-3 stems (which begin with the chapter letter), provides\nimplicit chapter awareness that makes it a strong initialiser for the\nStage-1 chapter router.\n\n---\n\n## E-002: Flat ICD-10 Baseline {#sec-exp-e002}\n\n**Hypothesis:** A flat 1,926-way ICD-10 classifier provides the most\ndirect comparison point for the hierarchical approach, and its encoder\nweights can serve as a warm-start initialiser for Stage-2 resolvers.\n\n**Setup:** Flat 1,926-way classification over all billable ICD-10 codes.\nThis is the hardest possible formulation of the problem.\n\n| Parameter | Value |\n|---|---|\n| Label scheme | Full ICD-10 (1,926 classes) |\n| Epochs | 40 |\n| Learning rate | 2×10⁻⁵ |\n| Training records | 7,728 |\n\n**Result:**\n\n| Metric | Value |\n|---|---|\n| Test accuracy | 73.3% |\n| Macro F1 | 0.634 |\n| Best epoch | 38 |\n\n: E-002 results. {#tbl-exp-e002}\n\n**Interpretation:** 73.3% accuracy on a 1,926-way classification task from\n~4 training examples per class is a reasonable flat baseline. The model\nconverges at epoch 38 rather than 40, indicating the training budget is\nappropriate.\n\nThe Macro F1 of 0.634 reflects the difficulty of the label space — with\nonly 4 training examples per code, many classes have limited within-class\nvariance and the model cannot always distinguish similar codes.\n\n**Chapter-level analysis:** Despite predicting full ICD-10 codes, the\nflat model achieves 90.3% accuracy at the chapter level — meaning 9 out of\n10 errors are within-chapter (the right chapter but wrong specific code)\nrather than cross-chapter. This foreshadows the hierarchical approach.\n\n**Role in subsequent experiments:** The 40-epoch E-002 encoder is the\ncritical warm-start initialiser for Stage-2 in E-010. The epoch count\nmatters — see @sec-exp-e010.\n\n---\n\n## E-003: Hierarchical Cold Start {#sec-exp-e003}\n\n**Hypothesis:** The hierarchical two-stage architecture produces better\nresults than flat ICD-10 classification even without special initialisation.\n\n**Setup:** Stage-1 router trained from E-001 weights (22-way chapter\nclassification). Stage-2 resolvers trained from base Bio_ClinicalBERT\n(cold start — no ICD-10 pre-training).\n\n**Result:**\n\n| Metric | Value |\n|---|---|\n| Stage-1 accuracy | 96.4% |\n| Stage-2 within-chapter | 11.7% |\n| E2E accuracy | 11.1% |\n| Macro F1 | 0.075 |\n\n: E-003 results. {#tbl-exp-e003}\n\n**Interpretation:** The architecture fails dramatically without warm\ninitialisation. Despite near-perfect chapter routing (96.4%), the within-chapter\nresolvers cannot learn from only ~4 training examples per code when starting\nfrom a general-domain language model.\n\nThis result is the most important in the experimental progression — it\nestablishes that the hierarchical architecture's value is entirely dependent\non how Stage-2 is initialised.\n\n::: {.callout-important}\n## The Cold Start Problem\n\nWith 4 training examples per code and up to 263 codes per chapter,\na Stage-2 resolver trained from scratch must learn to distinguish between\ncodes from an initialisation that has no ICD-10 knowledge. The gradient\nsignal is insufficient — the model cannot discriminate conditions it has\nno prior representation of.\n\nThe warm-start from E-002 solves this by providing an encoder that has\nalready learned to distinguish ICD-10 codes at the flat level. Stage-2\nfine-tuning then specialises these representations for the narrower\nwithin-chapter problem.\n:::\n\n---\n\n## E-009: Hierarchical with E-002 Warm Start (20 Epochs) {#sec-exp-e009}\n\n**Hypothesis:** Initialising Stage-2 resolvers from the E-002 flat ICD-10\nclassifier will dramatically improve within-chapter accuracy.\n\n**Setup:** Stage-1 router reused from E-003 (no retraining). Stage-2\nresolvers initialised from the E-002 encoder weights (20-epoch version),\nwith the 1,926-way classification head replaced by chapter-specific heads.\n\n**Result:**\n\n| Metric | Value |\n|---|---|\n| Stage-1 accuracy | 96.4% |\n| Stage-2 within-chapter | 82.2% |\n| E2E accuracy | 79.8% |\n| Macro F1 | 0.711 |\n\n: E-009 results. {#tbl-exp-e009}\n\n**Interpretation:** The hypothesis is confirmed dramatically. Warm\ninitialisation from E-002 improves within-chapter accuracy from 11.7% to\n82.2% — a +70.5 percentage point improvement. E2E accuracy jumps from 11.1%\nto 79.8%, surpassing the flat E-002 baseline by +6.5 percentage points.\n\nThe head-mismatch at load time (the 1,926-way head cannot transfer to an\nN-way head) is expected and handled correctly — only the encoder transfers,\nand the new classification head is randomly initialised and fine-tuned.\n\n::: {.callout-note}\n## The Head Swap Pattern\n\nWhen loading E-002 weights into a chapter-specific resolver:\n\n```\nBio_ClinicalBERT encoder (768-dim)  ← TRANSFERRED ✅\nLinear head (768 → 1,926)           ← DISCARDED\nLinear head (768 → N_chapter)       ← RANDOMLY INITIALISED, FINE-TUNED\n```\n\nThe encoder transfer is complete and correct. Only the final linear layer\nis reinitialised. HuggingFace reports this as \"missing keys\" and \"unexpected\nkeys\" — this is expected, not an error.\n:::\n\n---\n\n## E-010: Hierarchical with E-002 Warm Start (40 Epochs) {#sec-exp-e010}\n\n**Hypothesis:** A more thoroughly pre-trained E-002 initialiser (40 epochs\nvs 20 epochs) produces better Stage-2 representations and improves E2E accuracy.\n\n**Setup:** Identical to E-009 except Stage-2 resolvers are initialised from\nthe 40-epoch E-002 model rather than the 20-epoch version.\n\n**Result:**\n\n| Metric | Value |\n|---|---|\n| Stage-1 accuracy | 98.7% |\n| Stage-2 within-chapter | 84.8% |\n| E2E accuracy | **83.9%** |\n| Macro F1 | **0.762** |\n| ECE (post-calibration) | **0.034** |\n| Coverage@0.7 | **82.1%** |\n| Accuracy on covered | **95.2%** |\n\n: E-010 results — current best. {#tbl-exp-e010}\n\n**Interpretation:** The 40-epoch E-002 initialiser produces +4.1 percentage\npoints E2E accuracy over the 20-epoch version — a larger gain than any\narchitectural change tested. This confirms that the E-002 model has not\nconverged at 20 epochs and continues learning useful ICD-10 representations\nthrough epoch 40.\n\nNotably, Stage-1 accuracy also improves from 96.4% to 98.7%, likely due to\nimproved label-related representations propagating through the shared\nBio_ClinicalBERT backbone used across all stages.\n\n**Z-chapter improvement:** The most difficult chapter improves from 52.9%\n(E-009) to 62.1% (E-010) — a +9.2 percentage point gain. The 40-epoch\nencoder has substantially better Z-code discrimination, likely because the\nflat classifier was forced to learn finer distinctions between administrative\ncodes over the longer training run.\n\n---\n\n## Experiment Summary {#sec-exp-summary}\n\n::: {#tbl-exp-summary .cell tbl-cap='🏆 Complete experiment progression showing E2E accuracy and Macro F1.' execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| ID        | Description                         | Architecture   | Init                    | E2E Acc   | Macro F1   |\n|:----------|:------------------------------------|:---------------|:------------------------|:----------|:-----------|\n| E-001     | ICD-3 flat (675 classes)            | Flat           | Bio_ClinicalBERT        | 87.2%*    | 0.841      |\n| E-002     | ICD-10 flat (1,926 classes)         | Flat           | Bio_ClinicalBERT        | 73.3%     | 0.634      |\n| E-003     | Hierarchical, cold start            | Hierarchical   | Bio_ClinicalBERT (cold) | 11.1%     | 0.075      |\n| E-009     | Hierarchical, E-002 init (20ep)     | Hierarchical   | E-002 (20 epochs)       | 79.8%     | 0.711      |\n| **E-010** | **Hierarchical, E-002 init (40ep)** | Hierarchical   | E-002 (40 epochs)       | **83.9%** | **0.762**  |\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n*E-001 predicts ICD-3 stems (675 classes), not full ICD-10 codes — not directly comparable.\n```\n:::\n:::\n\n\n### Key Findings\n\n**Finding 1: Architecture requires warm initialisation.** The cold-start\nresult (E-003, 11.1%) demonstrates that the hierarchical architecture has\nno intrinsic advantage over flat classification — its benefit is entirely\ndelivered through the warm-start mechanism. Without pre-trained ICD-10\nrepresentations in the Stage-2 encoder, the architecture fails.\n\n**Finding 2: Pre-training depth matters.** The +4.1pp improvement from\n20-epoch to 40-epoch E-002 initialisation (E-009 → E-010) is larger than\nthe improvement from flat to hierarchical architecture at the same\ninitialisation depth. Investing compute in the pre-training stage pays\ndividends in the downstream task.\n\n**Finding 3: Hierarchical beats flat at the same initialisation budget.**\nE-010 (hierarchical, 40-epoch init) achieves 83.9% vs E-002 (flat, 40\nepochs) at 73.3% — a +10.6 percentage point improvement. The hierarchical\ndecomposition genuinely helps when the encoder is well-initialised.\n\n**Finding 4: The previous production pipeline is now beaten without its\nauxiliary components.** The previous best result (77.4%, using augmented\ngold data, a graph reranker, and Z-threshold overrides) is surpassed by\nE-010 (83.9%) using only the original gold data and standard training.\n\n",
    "supporting": [
      "05_experiments_files/figure-typst"
    ],
    "filters": []
  }
}