{
  "hash": "83af58a6a6a7efccb320a13ba27a53b6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Executive Summary\"\n---\n\n# Executive Summary\n\n::: {.callout-tip icon=false}\n## 🎯 The One-Paragraph Version\n\nWe built a system that reads clinical notes and automatically assigns the\ncorrect ICD-10 diagnostic code — the billing and classification code that\ndescribes a patient's condition. On a held-out test set of 966 records\ncovering 1,926 distinct codes, the system achieves **83.9% top-1 accuracy**\nand automatically codes **82.1% of cases** at **95.2% precision**,\nrouting the remaining 17.9% to human review. It does this without access\nto any real patient data, trained entirely on a high-quality synthetic dataset.\n:::\n\n---\n\n## The Problem {#sec-exec-problem}\n\nEvery clinical encounter in a hospital or clinic generates a medical note.\nFor that encounter to be billed — whether to an insurer, a government\nprogramme, or a patient — someone must translate the clinical language in\nthat note into a standardised diagnostic code from the ICD-10 classification\nsystem maintained by the World Health Organisation.\n\nThere are **1,926 billable ICD-10 codes** in the scope of this project.\nAssigning the right one requires clinical knowledge, familiarity with the\ncoding ruleset, and careful reading of often lengthy, unstructured free-text.\nToday this work is performed manually by trained medical coders — a slow,\nexpensive, and error-prone process.\n\nCoding errors and delays have real consequences:\n\n- **Claim denials** — incorrect codes trigger automatic claim rejection by\n  payers, costing providers revenue and administrative time.\n- **Revenue cycle delays** — manual coding creates a bottleneck between care\n  delivery and payment.\n- **Data quality** — coding inconsistency degrades the quality of population\n  health data, research datasets, and epidemiological surveillance.\n\nAutomated ICD-10 coding from clinical notes is one of the oldest and most\nstudied problems in clinical NLP. It remains unsolved at the scale of the\nfull ICD-10 code set.\n\n---\n\n## What We Built {#sec-exec-what}\n\nThe Notes-to-ICD-10 system is a two-stage hierarchical classification\npipeline built on top of `Bio_ClinicalBERT` — a version of BERT\npre-trained on clinical text from MIMIC-III.\n\n![The two-stage hierarchical approach: Stage 1 routes each note to the correct ICD-10 chapter; Stage 2 resolves the specific billable code within that chapter.](images/Two_stage_hierarchial_classification.png){#fig-two-stage fig-alt=\"Diagram showing flat 1926-way classification avoided, replaced by Stage 1 chapter routing and Stage 2 within-chapter resolution using M25.562 as example\"}\n\n**Stage 1 — Chapter Router:** A 22-way classifier that reads the clinical\nnote and routes it to the correct ICD-10 chapter (the top level of the\nhierarchy, identified by a single letter such as M for musculoskeletal or\nZ for administrative contacts). This router achieves 98.7% accuracy — nearly\nall notes are directed to the correct chapter.\n\n**Stage 2 — Code Resolver:** Nineteen per-chapter classifiers that predict\nthe specific ICD-10 code within the routed chapter. Each resolver handles\nbetween 12 and 263 codes. The resolvers are initialised from a flat ICD-10\nclassifier pre-trained for 40 epochs, which provides rich code representations\nbefore chapter-specific fine-tuning begins.\n\n**Confidence-gated output:** Every prediction comes with a calibrated\nconfidence score. Cases where the model is confident (≥0.7) are flagged\nfor automatic coding. Cases where the model is uncertain are routed to a\nhuman coder for review. This selective automation strategy achieves high\nprecision on auto-coded cases without sacrificing recall.\n\n---\n\n## Key Results {#sec-exec-results}\n\n::: {#tbl-exec-leaderboard .cell tbl-cap='🏆 Experiment leaderboard — all results on the same held-out test set of 966 records.' execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Experiment                  | Architecture                | E2E Accuracy   | Macro F1   | ECE       | Coverage@0.7   | Note                                       |\n|:----------------------------|:----------------------------|:---------------|:-----------|:----------|:---------------|:-------------------------------------------|\n| E-001 (ICD-3 flat baseline) | Flat, 675 classes           | 87.2%          | 0.841      | —         | —              | ICD-3 codes only — not directly comparable |\n| E-002 (ICD-10 flat)         | Flat, 1,926 classes         | 73.3%          | 0.634      | —         | —              | Flat baseline                              |\n| E-003 (cold start)          | Hierarchical, no init       | 11.1%          | 0.075      | —         | —              | Architecture without warm init             |\n| E-009 (20-epoch init)       | Hierarchical, E-002 init    | 79.8%          | 0.711      | —         | —              | 20-epoch E-002 initialiser                 |\n| **E-010 (best)**            | Hierarchical, 40-epoch init | **83.9%**      | **0.762**  | **0.034** | **82.1%**      | Current best                               |\n:::\n:::\n\n\nThe three headline findings:\n\n1. **Hierarchical architecture requires warm initialisation.** Without\n   pre-trained encoder weights (E-003), the architecture collapses to 11.1%\n   accuracy despite a near-perfect chapter router. With E-002 initialisation,\n   it reaches 79.8%.\n\n2. **Pre-training epoch count matters more than expected.** Doubling the\n   E-002 pre-training from 20 to 40 epochs adds +4.1 percentage points\n   E2E accuracy — a larger gain than any architectural change tested.\n\n3. **Selective automation is viable.** At a 0.7 confidence threshold,\n   82.1% of cases are auto-coded at 95.2% precision — a precision level\n   that meets or exceeds typical human coding accuracy for common codes.\n\n---\n\n## What This Is Not {#sec-exec-not}\n\nThis system was developed and evaluated entirely on **MedSynth** — a\nhigh-quality synthetic dataset of 10,240 clinical notes generated by GPT-4o\nwith balanced ICD-10 code coverage. It has **not** been validated on real\nclinical notes from a live health system.\n\nThe performance figures in this document reflect the system's capability on\nsynthetic data with a uniform code distribution. Real clinical data has a\nhighly skewed distribution — common codes appear thousands of times, rare\ncodes appear once or twice — and may use clinical language, abbreviations,\nand documentation styles that differ significantly from the synthetic notes.\n\nValidation on MIMIC-IV-Note (real de-identified discharge summaries from\nBeth Israel Deaconess Medical Center) is planned but currently blocked\npending PhysioNet data access approval.\n\n::: {.callout-warning}\n## Production Readiness\nThis system is a research prototype. It should not be used for live clinical\ncoding decisions without validation on real-world data from the target\nhealth system.\n:::\n\n---\n\n## Project at a Glance {#sec-exec-glance}\n\n| | |\n|---|---|\n| **Dataset** | MedSynth — 9,660 billable records, 1,926 ICD-10 codes |\n| **Model backbone** | `emilyalsentzer/Bio_ClinicalBERT` |\n| **Architecture** | Two-stage hierarchical: 22-way router + 19 resolvers |\n| **Training hardware** | Apple M5 Max (MPS acceleration) |\n| **Total training time** | ~12 hours (full experiment chain) |\n| **Best result** | 83.9% E2E accuracy, 0.762 Macro F1 |\n| **Auto-coding rate** | 82.1% at 95.2% precision (τ = 0.7) |\n| **Calibration quality** | ECE = 0.034 (well calibrated) |\n| **Codebase** | Python 3.12, HuggingFace Transformers, Polars, uv |\n| **Test coverage** | 94 unit tests, no GPU required |\n\n",
    "supporting": [
      "01_executive_summary_files/figure-typst"
    ],
    "filters": []
  }
}