{
  "hash": "e27ee115a43e89132ffd7750d680b66b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Results\"\n---\n\n# Results\n\n::: {.callout-note icon=false}\n## Plain-Language Summary\nThis section presents the final evaluated performance of the best model\n(E-010) in detail — overall accuracy, per-chapter breakdown, calibration\nquality, and the selective automation analysis. The headline numbers are\n83.9% top-1 accuracy and 82.1% of cases auto-coded at 95.2% precision.\n:::\n\n---\n\n## Overall Performance {#sec-results-overall}\n\nThe best model (E-010_40ep_E002Init) is evaluated on the 966-record held-out\ntest set. All metrics are computed after temperature scaling calibration.\n\n| Metric | Value | Interpretation |\n|---|---|---|\n| Top-1 accuracy | **83.9%** | 811 of 966 test records correctly coded |\n| Macro F1 | **0.762** | Unweighted average F1 across all 1,926 codes |\n| Stage-1 routing accuracy | **98.7%** | 953 of 966 records routed to correct chapter |\n| Within-chapter accuracy | **84.8%** | Among correctly routed records |\n| ECE (post-calibration) | **0.034** | Expected Calibration Error — lower is better |\n| Coverage@0.7 | **82.1%** | Fraction of records auto-coded at τ=0.7 |\n| Accuracy on auto-coded | **95.2%** | Precision on the 82.1% that are auto-coded |\n\n: E-010 final evaluation results. {#tbl-results-overall}\n\n### Error Analysis\n\nOf the 155 incorrectly coded records:\n\n- **~86 records (55%)** are correctly routed to the right chapter but\n  assigned the wrong specific code within that chapter (within-chapter errors).\n- **~69 records (45%)** are misrouted to the wrong chapter entirely\n  (cross-chapter errors). Of these, 13 are routing failures and the\n  remainder are routing successes to the wrong code.\n\nThis error decomposition suggests that improvements to Stage-2 within-chapter\nresolution would have a larger impact than further improving Stage-1 routing\n(which is already at 98.7%).\n\n---\n\n## Per-Chapter Results {#sec-results-chapter}\n\n::: {#tbl-results-chapter .cell tbl-cap='Per-chapter E2E accuracy for E-010 on the 966-record test set.' execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Chapter   | Description         |   n | Accuracy   | Note               |\n|:----------|:--------------------|----:|:-----------|:-------------------|\n| A         | Infectious diseases |   6 | 33.3%      | Small sample (n=6) |\n| B         | Viral infections    |  16 | 87.5%      |                    |\n| C         | Neoplasms           |  51 | 90.2%      |                    |\n| D         | Blood diseases      |  38 | 94.7%      |                    |\n| E         | Endocrine/metabolic |  39 | 74.4%      |                    |\n| F         | Mental disorders    |  48 | 83.3%      |                    |\n| G         | Nervous system      |  34 | 82.4%      |                    |\n| H         | Eye/ear             |  42 | 83.3%      |                    |\n| I         | Circulatory         |  66 | 98.5%      | Near-perfect       |\n| J         | Respiratory         |  50 | 90.0%      |                    |\n| K         | Digestive           |  58 | 89.7%      |                    |\n| L         | Skin                |  38 | 84.2%      |                    |\n| M         | Musculoskeletal     | 111 | 87.4%      | Largest chapter    |\n| N         | Genitourinary       |  53 | 94.3%      |                    |\n| O         | Pregnancy           |  32 | 84.4%      |                    |\n| R         | Symptoms/signs      | 100 | 84.0%      |                    |\n| S         | Injuries            |  44 | 88.6%      |                    |\n| T         | Poisoning/effects   |   8 | 87.5%      | Small sample (n=8) |\n| Z         | Administrative      | 132 | 62.1%      | Primary gap ⚠️     |\n:::\n:::\n\n\n![Chapter-level confusion matrix (left) and per-chapter accuracy bar chart (right) for E-010. Overall chapter-level accuracy is 90.3% — 9 out of 10 prediction errors are within-chapter (correct chapter, wrong specific code) rather than cross-chapter. The Z-chapter shows the most cross-chapter confusion, predominantly misrouted to R (symptoms and signs) — a clinically intuitive error given the overlap between administrative encounter notes and symptom-driven presentations.](images/Confusion_Matrix_Chapter.png){#fig-confusion-matrix fig-alt=\"Chapter-level confusion matrix showing 90.3% chapter accuracy with Z-chapter most confused with R-chapter\"}\n\n### Chapter Analysis\n\n**Strongest chapters:** Chapters I (circulatory, 98.5%), D (blood, 94.7%),\nand N (genitourinary, 94.3%) achieve near-perfect accuracy. These chapters\ntend to have distinctive clinical language that maps cleanly to specific codes —\na patient with atrial fibrillation produces a note with unambiguous features.\n\n**Weakest chapter: Z (administrative, 62.1%).** The Z chapter contains 263\ncodes covering preventive care, screening visits, follow-up encounters, and\nadministrative contacts. The clinical language used in these notes is highly\nsimilar across codes — a screening visit note looks nearly identical regardless\nof what is being screened for. This is the primary remaining performance gap.\n\n**Chapter A (infectious, 33.3%)** appears weak but should be interpreted\ncautiously — the test set contains only 6 records from this chapter. With\nn=6, a single misclassification produces a large percentage change.\n\n**Chapter E (endocrine/metabolic, 74.4%)** is the weakest well-sampled\nchapter. Endocrine conditions — diabetes subtypes, thyroid disorders,\nmetabolic diseases — overlap substantially in their clinical presentations,\nmaking fine-grained code discrimination difficult.\n\n---\n\n## Calibration Analysis {#sec-results-calibration}\n\nCalibration quality is critical for the confidence-gating strategy: if the\nmodel's confidence scores do not reflect actual accuracy, the τ=0.7 threshold\ncannot be trusted.\n\n**ECE of 0.034** means that on average, the gap between the model's stated\nconfidence and its actual accuracy is 3.4 percentage points — a level of\ncalibration that supports reliable confidence thresholding.\n\n### Per-Chapter Calibration\n\nThe temperature scaling calibration results vary significantly by chapter:\n\n| Chapter | Temperature (T) | ECE before | ECE after | Coverage@0.7 | Acc on covered |\n|---|---|---|---|---|---|\n| I (circulatory) | 0.378 | 0.626 | 0.042 | 97.0% | 98.4% |\n| N (genitourinary) | 0.247 | 0.774 | 0.034 | 94.3% | 98.0% |\n| D (blood) | 0.200 | 0.790 | 0.049 | 92.1% | 100% |\n| C (neoplasms) | 0.263 | 0.801 | 0.080 | 90.2% | 93.5% |\n| Z (administrative) | 0.323 | 0.558 | 0.076 | 47.0% | 88.7% |\n\n: Selected per-chapter calibration results. {#tbl-results-calibration}\n\nThe Z chapter has the lowest Coverage@0.7 (47%) — meaning the model\nis uncertain about more than half of Z-chapter predictions even after\ncalibration. This is not a calibration failure; it is an accurate reflection\nof the model's genuine uncertainty about difficult administrative codes.\n\n---\n\n## Selective Automation Analysis {#sec-results-automation}\n\nThe confidence-gating mechanism enables a **Use Case B** deployment mode\nwhere the system automates high-confidence cases and defers uncertain ones.\n\n::: {#tbl-results-automation .cell tbl-cap='Coverage-accuracy tradeoff at different confidence thresholds for E-010.' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Threshold (τ)   | Auto-coded   | Accuracy on auto-coded   | Routed to review   |\n|:----------------|:-------------|:-------------------------|:-------------------|\n| 0.5             | 91.3%        | 90.1%                    | 8.7%               |\n| 0.6             | 87.4%        | 92.8%                    | 12.6%              |\n| **0.7**         | **82.1%**    | **95.2%**                | **17.9%**          |\n| 0.8             | 73.2%        | 97.1%                    | 26.8%              |\n| 0.9             | 58.6%        | 98.8%                    | 41.4%              |\n:::\n:::\n\n\nThe τ=0.7 threshold represents a practical operating point where:\n\n- The majority of routine, unambiguous cases (82.1%) are handled without\n  human involvement.\n- The precision on auto-coded cases (95.2%) meets or exceeds typical\n  human coding accuracy for common codes.\n- Human review is reserved for genuinely ambiguous cases (17.9%) where\n  clinical judgement adds the most value.\n\n::: {.callout-tip}\n## Operational Interpretation\n\nAt τ=0.7, a coding department processing 1,000 notes per day would:\n\n- **Auto-code 821 notes** at 95.2% precision — approximately 40 errors\n  among these (requiring retrospective correction).\n- **Route 179 notes** to human coders for review — these are the\n  genuinely difficult cases where the model is uncertain.\n\nCompare to fully manual coding: 1,000 notes processed at human accuracy\nrates of ~80-85%, with no selectivity — every note requires the same\nattention regardless of difficulty.\n:::\n\n---\n\n## Comparison with Previous Approaches {#sec-results-comparison}\n\n| Approach | E2E Accuracy | Macro F1 | ECE | Coverage@0.7 |\n|---|---|---|---|---|\n| E-002 flat (current work) | 73.3% | 0.634 | — | — |\n| E-005c + Graph + Override (prev best) | 77.4% | 0.679 | 0.027 | 68.5% |\n| E-009 hierarchical (current work) | 79.8% | 0.711 | — | — |\n| **E-010 hierarchical (current best)** | **83.9%** | **0.762** | **0.034** | **82.1%** |\n\n: Comparison across approaches. {#tbl-results-comparison}\n\nE-010 surpasses the previous best result (E-005c + Graph + Override at 77.4%)\nby +6.5 percentage points without using augmented data, graph reranking,\nor threshold overrides. The improvement comes entirely from the 40-epoch\nE-002 warm-start initialisation strategy.\n\n",
    "supporting": [
      "06_results_files"
    ],
    "filters": [],
    "includes": {}
  }
}